import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Escolha os pesos que você quer usar
})
const geistSans = localFont({
  src: "./fonts/Montserrat-Bold.woff",
  weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}   antialiased`}>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
